# ==========================================
# CORE CONFIG
# ==========================================
set -g default-shell pwsh
set -g default-command nu
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix
set-option -g mouse on
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g history-limit 100000

# Open new windows in CWD
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Status Bar Configuration
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-style bg=#1e1e2e,fg=#cdd6f4

set -g status-left-length 100
set -g status-right-length 100

# Integrated the current folder indicator into the left module
set -g status-left "#{?client_prefix,#[fg=white]#[bg=blue,bold] Wait ,} #[fg=#89b4fa,bold]  #{b:pane_current_path} "
set -g status-right "#[fg=#a6adc8] %Y-%m-%d #[fg=#1e1e2e,bg=#a6e3a1,bold] %H:%M "

set -g status-justify centre
set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=#f38ba8,bold] [ #I:#W ] "
